#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "PYFILE is not set. Please set it."
    exit 1
fi

BASENAME=$(basename "$PYFILE" .py)

SCRIPT_DIR=$(dirname "$PYFILE")

cd "$SCRIPT_DIR" || exit 1

python3 -m py_compile "$PYFILE"

if [ $? -eq 0 ]; then
    echo "Compiling $PYFILE ..."
    mv "__pycache__/$BASENAME.pyc" "$BASENAME.pyc"
    rmdir "__pycache__"
else
    echo "Compilation of $PYFILE failed."
    exit 1
fi
